### ISSUE TITLE
Just wanted to say that this project is awesome

### ISSUE THREAD

**Issue by transitive-bullshit** [mattdesl/mp4-wasm#2]
Lots of apps can benefit from this type of WASM solution as opposed to bundling a full build of ffmpeg client-side or (even more work) adding to an async task queue for backend rendering.

Great job, Matt -- feel free to close this issue 😄

**Comment by transitive-bullshit** [comment]
Also, are you sure you want to publish your `build/` artifacts to GitHub?

**Comment by mattdesl** [comment]
Thanks!
