### ISSUE TITLE
Patents

### ISSUE THREAD

**Issue by davedoesdev** [mattdesl/mp4-wasm#4]
Is MP4 patent-encumbered?

**Comment by mattdesl** [comment]
I don't believe so. It may be tied to some patents but it's generally not regarded as encumbered by them. The main issue lies with H264 encoding which is heavily 'policed' by the patent holders, and which isn't part of this repo.

(Just FYI — IANAL)

**Comment by davedoesdev** [comment]
NP, thanks for the update.
And: IANAL!
